application:
  jwt:
    secretKey: ",:S:5s[>I]{`)UY-G^5cL%fttbM7:YVIX4>#Ng~dF5SG<D^3L?7"
    tokenPrefix: "Bearer "
    tokenExpirationHours: 1
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmdb?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: admdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org:
      root: WARN
      hibernate:
        SQL: WARN
        type:
          descriptor: WARN
    blog: WARN
#server:
#  port: 8000
